
// Copyright by libARMAS authors. See AUTHORS file in this archive.

// This file is part of libARMAS library. It is free software,
// distributed under the terms of GNU Lesser General Public License Version 3, or
// any later version. See the COPYING file included in this archive.

//! \file
//! Generate the orthogonal matrix of QR factorization

#include "dtype.h"
#include "dlpack.h"

// -----------------------------------------------------------------------------
// this file provides following type dependent functions
#if defined(armas_qrbuild) && defined(armas_qrbuild_w)
#define ARMAS_PROVIDES 1
#endif
// this file requires external public functions
#if defined(armas_blas1)
#define ARMAS_REQUIRES 1
#endif

// compile if type dependent public function names defined
#if (defined(ARMAS_PROVIDES) && defined(ARMAS_REQUIRES)) || defined(CONFIG_NOTYPENAMES)
// -----------------------------------------------------------------------------


#include "matrix.h"
#include "internal.h"
#include "internal_lapack.h"
#include "partition.h"

#ifndef ARMAS_BLOCKING_MIN
#define ARMAS_BLOCKING_MIN 32
#endif

static inline int __ws_qrbuild(int M, int N, int lb)
{
    return lb > 0 ? lb * N : N;
}

/*
 * Unblocked code for generating M by N matrix Q with orthogonal columns which
 * are defined as the first N columns of the product of K first elementary
 * reflectors.
 *
 * Parameters nk = n(A)-K, mk = m(A)-K define the initial partitioning of
 * matrix A.
 *
 *  Q = H(1)H(2)...H(k)  , 0 < k <= N, where H(i) = I - tau*v*v.T
 *
 * Computation is ordered as H(1)*(H(2)...*(H(k)*I)) ie. from right to left.
 *
 * If k < N columns k+1:N are cleared and diagonal entries [k+1:N,k+1:N] are
 * set to unit. Then the matrix Q is generated by left multiplying elements right
 * of i'th elementary reflector H(i).
 * 
 * Compatible to lapack.xORG2R subroutine.
 */
static
int unblk_qrbuild(armas_dense_t * A, armas_dense_t * tau,
                  armas_dense_t * W, int mk, int nk, int mayclear,
                  armas_conf_t * conf)
{
    armas_dense_t ATL, ATR, ABR, A00, a01, a11, a12, a21, A22;
    armas_dense_t tT, tB, t0, t1, t2, w12, D;
    DTYPE tauval;
    DTYPE *wdata = armas_data(W);

    EMPTY(ATL);
    EMPTY(A00);
    EMPTY(a11);

    mat_partition_2x2(
        &ATL, &ATR,
        __nil, &ABR, /**/ A, mk, nk, ARMAS_PBOTTOMRIGHT);
    mat_partition_2x1(
        &tT,
        &tB, /**/ tau, nk, ARMAS_PBOTTOM);

    // zero the right side
    if (nk > 0 && mayclear) {
        armas_mscale(&ATR, ZERO, 0, conf);
        armas_mscale(&ABR, ZERO, 0, conf);
        armas_diag(&D, &ABR, 0);
        armas_madd(&D, ONE, 0, conf);
    }

    while (ATL.rows > 0 && ATL.cols > 0) {
        mat_repartition_2x2to3x3(
            &ATL,
            &A00, &a01, __nil,
            __nil, &a11, &a12,
            __nil, &a21, &A22, /**/ A, 1, ARMAS_PTOPLEFT);
        mat_repartition_2x1to3x1(
            &tT,
            &t0, &t1, &t2, /**/ tau, 1, ARMAS_PTOP);
        // ---------------------------------------------------------------------
        armas_make(&w12, a12.cols, 1, a12.cols, wdata);
        armas_apply_householder2x1(&t1, &a21,
                                     &a12, &A22, &w12, ARMAS_LEFT, conf);

        tauval = armas_get(&t1, 0, 0);
        armas_scale(&a21, -tauval, conf);
        armas_set(&a11, 0, 0, ONE - tauval);

        // zero
        armas_scale(&a01, 0.0, conf);
        // ---------------------------------------------------------------------
        mat_continue_3x3to2x2(
            &ATL, &ATR,
            __nil, &ABR, /**/ &A00, &a11, &A22, A, ARMAS_PTOPLEFT);
        mat_continue_3x1to2x1(
            &tT,
            &tB, /**/ &t0, &t1, tau, ARMAS_PTOP);
    }
    return 0;
}

/*
 * Blocked code for generating M by N matrix Q with orthogonal columns which
 * are defined as the first N columns of the product of K first elementary
 * reflectors.
 *
 * If the number K of elementary reflectors is not multiple of the blocking
 * factor lb, then unblocked code is used first to generate the lower right corner
 * of the matrix Q. 
 *
 * Compatible with lapack.DORGQR subroutine.
 */
static
int blk_qrbuild(armas_dense_t * A, armas_dense_t * tau,
                armas_dense_t * T, armas_dense_t * W, int K, int lb,
                armas_conf_t * conf)
{
    armas_dense_t ATL, ATR, ABR, A00, A01, A11, A12, A21, A22, AL;
    armas_dense_t tT, tB, t0, t1, t2, D, Wrk;
    int nk, mk, uk;

    nk = A->cols - K;
    mk = A->rows - K;
    uk = K % lb;

    EMPTY(ATL);
    EMPTY(A00);

    mat_partition_2x2(
        &ATL, &ATR,
        __nil, &ABR, /**/ A, mk + uk, nk + uk, ARMAS_PBOTTOMRIGHT);
    mat_partition_2x1(
        &tT,
        &tB, /**/ tau, nk + uk, ARMAS_PBOTTOM);

    // zero the right side
    if (nk + uk > 0) {
        armas_mscale(&ATR, ZERO, 0, conf);
        if (uk > 0) {
            // blocking factor not multiple of K, do the first uk
            // columns with unblocked code
            unblk_qrbuild(&ABR, &tB, W, ABR.rows-uk, ABR.cols-uk, TRUE, conf);
        } else {
            // blocking factor is multiple of K
            armas_mscale(&ABR, ZERO, 0, conf);
            armas_diag(&D, &ABR, 0);
            armas_madd(&D, ONE, 0, conf);
        }
    }

    while (ATL.rows > 0 && ATL.cols > 0) {
        mat_repartition_2x2to3x3(
            &ATL,
            &A00,  &A01, __nil,
            __nil, &A11, &A12,
            __nil, &A21, &A22, /**/ A, lb, ARMAS_PTOPLEFT);
        mat_repartition_2x1to3x1(
            &tT,
            &t0, &t1, &t2, /**/ tau, lb, ARMAS_PTOP);
        // ---------------------------------------------------------------------
        mat_merge2x1(&AL, &A11, &A21);

        // block reflector
        armas_unblk_qr_reflector(T, &AL, &t1, conf);

        // update rightside i.e A12, A22
        armas_make(&Wrk, A12.cols, A12.rows, A12.cols, armas_data(W));
        armas_update_qr_left(&A12, &A22, &A11, &A21, T, &Wrk, FALSE, conf);

        // update current block
        unblk_qrbuild(&AL, &t1, W, A21.rows, 0, FALSE, conf);

        // zero top rows
        armas_mscale(&A01, ZERO, 0, conf);
        // ---------------------------------------------------------------------
        mat_continue_3x3to2x2(
            &ATL, &ATR,
            __nil, &ABR, /**/ &A00, &A11, &A22, A, ARMAS_PTOPLEFT);
        mat_continue_3x1to2x1(
            &tT,
            &tB, /**/ &t0, &t1, tau, ARMAS_PTOP);
    }
    return 0;
}


/**
 * @brief Generate the orthogonal matrix Q
 *
 * @see armas_qrbuild_w
 * @ingroup lapack
 */
int armas_qrbuild(armas_dense_t * A,
                    const armas_dense_t * tau, int K, armas_conf_t * cf)
{
    if (!cf)
        cf = armas_conf_default();

    int err;
    armas_wbuf_t *wbs, wb = ARMAS_WBNULL;
    if ((err = armas_qrbuild_w(A, tau, K, &wb, cf)) < 0)
        return err;

    wbs = &wb;
    if (wb.bytes > 0) {
        if (!armas_walloc(&wb, wb.bytes)) {
            cf->error = ARMAS_EMEMORY;
            return -ARMAS_EMEMORY;
        }
    } else
        wbs = ARMAS_NOWORK;

    err = armas_qrbuild_w(A, tau, K, wbs, cf);
    armas_wrelease(&wb);
    return err;
}


/**
 * @brief Generate the orthogonal matrix Q
 *
 * Generate the M by N matrix Q with orthogonal columns which
 * are defined as the first N columns of the product of K first elementary
 * reflectors.
 *
 * @param[in,out]  A
 *   On entry, the elementary reflectors as returned by armas_qrfactor().
 *   stored below diagonal of the M by N matrix A.
 *   On exit, the orthogonal matrix Q
 *
 * @param[in]  tau
 *   Scalar coefficents of elementary reflectors
 *
 * @param[in]  K
 *   The number of elementary reflectors whose product define the matrix Q
 *
 * @param[in]  wb
 *   Workspace. If *wb.bytes* is zero then size of required workspace in computed and returned
 *   immediately.
 *
 * @param[in,out] conf
 *   Configuration options.
 *
 *  @retval  0 Success
 *  @retval <0 Failure, `conf.error` set to last error
 *
 *  Last error codes returned
 *   - `ARMAS_EINVAL` A or tau is null pointer
 *   - `ARMAS_EWORK`  if no workspace or it is less than required for unblocked computation
 *
 * Compatible with lapackd.ORGQR.
 * @ingroup lapack
 */
int armas_qrbuild_w(armas_dense_t * A,
                      const armas_dense_t * tau,
                      int K, armas_wbuf_t * wb, armas_conf_t * conf)
{
    armas_dense_t T, Wrk;
    armas_env_t *env;
    size_t wsmin, wsz = 0;
    int lb;
    DTYPE *buf;

    if (!conf)
        conf = armas_conf_default();

    if (!A) {
        conf->error = ARMAS_EINVAL;
        return -ARMAS_EINVAL;
    }
    env = armas_getenv();
    if (wb && wb->bytes == 0) {
        if (env->lb > 0 && A->cols > env->lb)
            wb->bytes = (A->cols * env->lb) * sizeof(DTYPE);
        else
            wb->bytes = A->cols * sizeof(DTYPE);
        return 0;
    }

    if (!tau) {
        conf->error = ARMAS_EINVAL;
        return -ARMAS_EINVAL;
    }

    lb = env->lb;
    wsmin = A->cols * sizeof(DTYPE);
    if (!wb || (wsz = armas_wbytes(wb)) < wsmin) {
        conf->error = ARMAS_EWORK;
        return -ARMAS_EWORK;
    }
    // adjust blocking factor for workspace
    if (lb > 0 && A->cols > lb) {
        wsz /= sizeof(DTYPE);
        if (wsz < A->cols * lb) {
            lb = (wsz / A->cols) & ~0x3;
            if (lb < ARMAS_BLOCKING_MIN)
                lb = 0;
        }
    }

    wsz = armas_wpos(wb);
    buf = (DTYPE *) armas_wptr(wb);

    if (lb == 0 || A->cols <= lb) {
        armas_make(&Wrk, A->cols, 1, A->cols, buf);
        unblk_qrbuild(A, (armas_dense_t *) tau, &Wrk, A->rows-K,
                      A->cols-K, TRUE, conf);
    } else {
        // block reflector at start of workspace; other temporary space after
        armas_make(&T, lb, lb, lb, buf);
        armas_make(&Wrk, A->cols-lb, lb, A->cols-lb, &buf[armas_size(&T)]);

        blk_qrbuild(A, (armas_dense_t *) tau, &T, &Wrk, K, lb, conf);
    }
    armas_wsetpos(wb, wsz);

    return 0;
}
#else
#warning "Missing defines. No code!"
#endif /* ARMAS_PROVIDES && ARMAS_REQUIRES */
