
CC = gcc
THREADS = -pthread
OPT = -g -O3 -ffast-math -fomit-frame-pointer $(THREADS) -I../../src -I../
ARCH = -march=native

LIBDIR := ../../src/.libs
LIB := libarmasd.a

TESTS = gemm symm trmm trsm syrk trmrk ger trmv trsv

HELPER = ../helper.c

INCLUDES = ../../src/armas/dmatrix.h ../../src/armas/armas.h ../helper.h

check: $(TESTS)
       @for p in $(TESTS); do \
       	   ./$$p; \
	done	  

gemm: gemm.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ gemm.c $(HELPER) $(LIBDIR)/$(LIB)

symm: symm.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ symm.c $(HELPER) $(LIBDIR)/$(LIB)

trmm: trmm.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ trmm.c $(HELPER) $(LIBDIR)/$(LIB)

trsm: trsm.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ trsm.c $(HELPER) $(LIBDIR)/$(LIB)

trmrk: trmrk.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ trmrk.c $(HELPER) $(LIBDIR)/$(LIB)

syrk: syrk.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ syrk.c $(HELPER) $(LIBDIR)/$(LIB)

ger: ger.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ ger.c $(HELPER) $(LIBDIR)/$(LIB)

trmv: trmv.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ trmv.c $(HELPER) $(LIBDIR)/$(LIB)

trsv: trsv.c $(HELPER) $(LIBDIR)/$(LIB) $(INCLUDES)
	$(CC) $(OPT)  -lm -o $@ trsv.c $(HELPER) $(LIBDIR)/$(LIB)

.PHONY: clean
clean:
	rm -f $(TESTS)
	rm -f *~
